25 implement navigation from dashboard to detailed view with context
Code-Hauptwache/DroneDeck pull request #54
Opened 2024-12-31 10:12 UTC by zakaBouj

2025-01-01 11:25 UTC, zakaBouj commented
I pulled the state of [PR #47](https://github.com/Code-Hauptwache/DroneDeck/pull/47) since in that PR I implemented the `DashboardDroneCard` component which is used in this PR for switching from the card view to the detailed view of the card. Please consider reviewing PR #47 first if not already done before reviewing this PR.

2025-01-02 12:02 UTC, Gord310 commented
I will review this as soon as we merged #47 because I can't really make out the new changes to #47 :/

2025-01-02 12:31 UTC, Gord310 requested changes
The logic to check/display the "TravelDistance" would be better off in its own function. Either a private function in the DroneDashboardCard or the DroneDashboardCardDto

2025-01-02 12:31 UTC, Gord310 commented on src/main/java/ui/components/DroneDashboardCard.java
> +                                ? dto.getTravelDistance().toString()
I think putting this logic into a new function, “getTravelDistanceString(),” would be easier to understand.
The function would either return the travel distance as a string or return 'N/A' if no travel distance could be calculated.

2025-01-02 13:24 UTC, Gord310 approved these changes
LGTM

2025-01-02 13:24 UTC, merged